"""empty message

Revision ID: 416316fa5b99
Revises: c0fcde5d38dd
Create Date: 2017-12-12 19:29:46.997145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416316fa5b99'
down_revision = 'c0fcde5d38dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calibration_files_calibration_id_fkey', 'calibration_files', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('calibration_files_calibration_id_fkey', 'calibration_files', 'calibrations', ['calibration_id'], ['id'])
    # ### end Alembic commands ###
