"""empty message

Revision ID: 8850241daa95
Revises: 89abb08259fb
Create Date: 2017-12-11 21:48:05.607415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8850241daa95'
down_revision = '89abb08259fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csv_path', sa.Text(), nullable=True),
    sa.Column('txt_path', sa.Text(), nullable=True),
    sa.Column('micromatter_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calibration_files')
    # ### end Alembic commands ###
