"""empty message

Revision ID: c0fcde5d38dd
Revises: d93de7bc9c7f
Create Date: 2017-12-12 19:28:10.741734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fcde5d38dd'
down_revision = 'd93de7bc9c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibration_files', sa.Column('calibration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calibration_files', 'calibrations', ['calibration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calibration_files', type_='foreignkey')
    op.drop_column('calibration_files', 'calibration_id')
    # ### end Alembic commands ###
