"""empty message

Revision ID: c5c0c9bf5921
Revises: 868f8ec52b41
Create Date: 2017-12-12 18:31:03.466978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c0c9bf5921'
down_revision = '868f8ec52b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibration_files', sa.Column('calibration_id', sa.Integer(), nullable=True))
    op.drop_constraint('calibration_files_user_id_fkey', 'calibration_files', type_='foreignkey')
    op.create_foreign_key(None, 'calibration_files', 'calibrations', ['calibration_id'], ['id'])
    op.drop_column('calibration_files', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibration_files', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'calibration_files', type_='foreignkey')
    op.create_foreign_key('calibration_files_user_id_fkey', 'calibration_files', 'users', ['user_id'], ['id'])
    op.drop_column('calibration_files', 'calibration_id')
    # ### end Alembic commands ###
