"""empty message

Revision ID: d93de7bc9c7f
Revises: 76a53c12c37f
Create Date: 2017-12-12 19:22:11.716679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93de7bc9c7f'
down_revision = '76a53c12c37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calibration_files_calibration_id_fkey', 'calibration_files', type_='foreignkey')
    op.drop_column('calibration_files', 'calibration_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibration_files', sa.Column('calibration_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('calibration_files_calibration_id_fkey', 'calibration_files', 'calibrations', ['calibration_id'], ['id'])
    # ### end Alembic commands ###
