"""empty message

Revision ID: e89556e58d72
Revises: 416316fa5b99
Create Date: 2017-12-12 19:50:33.814957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89556e58d72'
down_revision = '416316fa5b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'calibration_files', 'calibrations', ['calibration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calibration_files', type_='foreignkey')
    # ### end Alembic commands ###
